version: '3.8'

services:
  profile-service:
    image: profileservice
    container_name: profile-service
    build:
      context: ./back-end/profile-service/
    environment:
      - MongoDbSettings_DatabaseName=Tender
      - MongoDbSettings_ConnectionString=${DB_URL_TENDER}
    restart: on-failure
    depends_on: rabbitmq
  
  apiGateway:
    image: apigateway
    container_name: api-gateway
    build:
      context: ./back-end/apiGateway/
    ports:
      - 7000:80
  
  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
    - 5656:5656
    - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 2