version: '3.8'

services:
  profile-service:
    image: profileservice
    container_name: profile-service
    build:
      context: ./back-end/profile-service/
    restart: on-failure
    depends_on:
     - rabbitmq
    #  - mongo
  
  match-service:
    image: matchservice
    container_name: match-service
    build:
      context: ./back-end/match-service/
    restart: on-failure
    depends_on:
      - rabbitmq
      # - mongo

  apiGateway:
    image: apigateway
    container_name: api-gateway
    build:
      context: ./back-end/apiGateway/
    ports:
      - 7000:80
  
  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
    - 15672:15672
    - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 2

  # mongo:
  #   image: mongo:latest
  #   environment:
  #     - MongoDbSettings_DatabaseName=${DB_NAME}
  #     - MongoDbSettings_ConnectionString=${DB_URL_TENDER}
  #   ports:
  #     - 1511:1511