name: ACR
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.ACR_ENDPOINT}}
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}
      -
        name: Docker Build
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./back-end/apiGateway
          file: ./back-end/apiGateway/Dockerfile
          push: true
          tags: ${{secrets.ACR_ENDPOINT}}/api-gateway:latest
      -
        name: Build and push profile-service
        uses: docker/build-push-action@v4
        with:
          context: ./back-end/profile-service
          file: ./back-end/profile-service/Dockerfile
          push: true
          tags: ${{secrets.ACR_ENDPOINT}}/profile-service:latest
      -
        name: Build and push match-service
        uses: docker/build-push-action@v4
        with:
          context: ./back-end/match-service
          file: ./back-end/match-service/Dockerfile
          push: true
          tags: ${{secrets.ACR_ENDPOINT}}/match-service:latest
      -
        name: Build and push auth-service
        uses: docker/build-push-action@v4
        with:
          context: ./back-end/auth-service
          file: ./back-end/auth-service/Dockerfile
          push: true
          tags: ${{secrets.ACR_ENDPOINT}}/match-service:latest
