name: docker
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      -
        name: Docker Build
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./back-end/apiGateway/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/api-gateway:latest
      -
        name: Build and push profile-service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./back-end/profile-service/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/profile-service:latest
      -
        name: Build and push match-service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./back-end/match-service/Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/match-service:latest